version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-api-transfer-direct
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TransferDirect
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  api:
    build:
      context: .
      dockerfile: Presentation/Dockerfile
    container_name: api-transfer-direct
    ports:
      - "5000:80"
    depends_on:
      - mysql
volumes:
  mysql_data:
